---
kafka:
  #  version: 4.0.0
  #  metadataVersion: 4.0-IV3

  #  clusterName: kafka
  #  autoCreateTopics: "true"

  #  replication:
  #    defaultReplicationFactor: 1
  #    offsetsReplicationFactor: 1
  #    minInSyncReplicas: 1
  #    transactionStateReplicationFactor: 1
  #    transactionStateMinInSyncReplica: 1

  #  resources:
  #    memory: 1Gi
  #    cpuRequest: "1"
  #    cpuLimit: "2"

  topics: {}
  #  EXAMPLE
  #  - name: topic1
  #    replicas: 1
  #    partitions: 50

  users: {}
  #  EXAMPLE
  #   - name: user1
  #     authenticationType: tls
  #     authorizationType: simple
  #     acls:
  #       - type: topic
  #         name: topic1
  #         patternType: literal
  #         operations:
  #           - Describe
  #           - Read
  #           - Write
